"""empty message

Revision ID: 09af40967e84
Revises: 6db6f6d58a71
Create Date: 2022-05-25 21:22:51.984011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09af40967e84'
down_revision = '6db6f6d58a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventocharlas', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('eventoferiaempresas', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('eventospeedmeeting', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('presentacionproyectos', sa.Column('url', sa.String(length=516), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentacionproyectos', 'url')
    op.drop_column('eventospeedmeeting', 'url')
    op.drop_column('eventoferiaempresas', 'url')
    op.drop_column('eventocharlas', 'url')
    # ### end Alembic commands ###
