"""empty message

Revision ID: 687716c551ab
Revises: 96fa5aa12d8e
Create Date: 2022-05-04 23:25:17.384498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '687716c551ab'
down_revision = '96fa5aa12d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventoCharlas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=4096), nullable=True),
    sa.Column('presencialidad', sa.Boolean(), nullable=True),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('autor', sa.String(length=516), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventoSpeedMeeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presencialidad', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('horaInicio', sa.Time(), nullable=True),
    sa.Column('horaFin', sa.Time(), nullable=True),
    sa.Column('perfiles', sa.String(length=4096), nullable=True),
    sa.Column('pregunta', sa.String(length=4096), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentacionProyectos',
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presencial', sa.Boolean(), nullable=True),
    sa.Column('videojuegos', sa.Boolean(), nullable=True),
    sa.Column('disenoDigital', sa.Boolean(), nullable=True),
    sa.Column('cortosAnimacion', sa.Boolean(), nullable=True),
    sa.Column('ingenieria', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventocharlas')
    op.drop_table('presentacionproyectos')
    op.drop_table('eventospeedmeeting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventospeedmeeting',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('presencialidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('horaInicio', mysql.TIME(), nullable=True),
    sa.Column('horaFin', mysql.TIME(), nullable=True),
    sa.Column('perfiles', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('pregunta', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('aprobada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='eventospeedmeeting_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('presentacionproyectos',
    sa.Column('validado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('presencial', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('videojuegos', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('disenoDigital', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cortosAnimacion', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ingenieria', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='presentacionproyectos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('eventocharlas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tema', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('presencialidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('aprobada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('autor', mysql.VARCHAR(length=516), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='eventocharlas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('presentacionProyectos')
    op.drop_table('EventoSpeedMeeting')
    op.drop_table('EventoCharlas')
    # ### end Alembic commands ###
