"""empty message

Revision ID: 8520e8a162e0
Revises: a7122ee6f93d
Create Date: 2022-05-25 21:26:58.980911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8520e8a162e0'
down_revision = 'a7122ee6f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventocharlas', sa.Column('url', sa.String(length=516), nullable=False))
    op.add_column('eventoferiaempresas', sa.Column('url', sa.String(length=516), nullable=False))
    op.add_column('eventospeedmeeting', sa.Column('url', sa.String(length=516), nullable=False))
    op.add_column('presentacionproyectos', sa.Column('url', sa.String(length=516), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentacionproyectos', 'url')
    op.drop_column('eventospeedmeeting', 'url')
    op.drop_column('eventoferiaempresas', 'url')
    op.drop_column('eventocharlas', 'url')
    # ### end Alembic commands ###
