"""empty message

Revision ID: 96fa5aa12d8e
Revises: 79f24e8e6b3b
Create Date: 2022-05-04 23:18:20.364936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96fa5aa12d8e'
down_revision = '79f24e8e6b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventoCharlas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=4096), nullable=True),
    sa.Column('presencialidad', sa.Boolean(), nullable=True),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('autor', sa.String(length=516), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EventoSpeedMeeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presencialidad', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('horaInicio', sa.Time(), nullable=True),
    sa.Column('horaFin', sa.Time(), nullable=True),
    sa.Column('perfiles', sa.String(length=4096), nullable=True),
    sa.Column('pregunta', sa.String(length=4096), nullable=True),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presentacionProyectos',
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presencial', sa.Boolean(), nullable=True),
    sa.Column('videojuegos', sa.Boolean(), nullable=True),
    sa.Column('disenoDigital', sa.Boolean(), nullable=True),
    sa.Column('cortosAnimacion', sa.Boolean(), nullable=True),
    sa.Column('ingenieria', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('eventocharlas')
    op.drop_table('presentacionproyectos')
    op.drop_table('eventospeedmeeting')
    op.alter_column('empresas', 'validado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'password',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('empresas', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'confirmed',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'userHash',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'empresas', ['email'])
    op.create_unique_constraint(None, 'empresas', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_constraint(None, 'empresas', type_='unique')
    op.alter_column('empresas', 'userHash',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('empresas', 'confirmed',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'password',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('empresas', 'validado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('eventospeedmeeting',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('presencialidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('horaInicio', mysql.TIME(), nullable=True),
    sa.Column('horaFin', mysql.TIME(), nullable=True),
    sa.Column('perfiles', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('pregunta', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('aprobada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='eventospeedmeeting_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('presentacionproyectos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('presencial', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('videojuegos', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('disenoDigital', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cortosAnimacion', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ingenieria', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('validado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='presentacionproyectos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('eventocharlas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tema', mysql.VARCHAR(length=4096), nullable=True),
    sa.Column('presencialidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fecha', sa.DATE(), nullable=True),
    sa.Column('aprobada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('autor', mysql.VARCHAR(length=516), nullable=True),
    sa.Column('empresa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='eventocharlas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('presentacionProyectos')
    op.drop_table('EventoSpeedMeeting')
    op.drop_table('EventoCharlas')
    # ### end Alembic commands ###
