"""empty message

Revision ID: a7122ee6f93d
Revises: 09af40967e84
Create Date: 2022-05-25 21:24:31.927788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7122ee6f93d'
down_revision = '09af40967e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventocharlas', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('eventoferiaempresas', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('eventospeedmeeting', sa.Column('url', sa.String(length=516), nullable=True))
    op.add_column('presentacionproyectos', sa.Column('url', sa.String(length=516), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentacionproyectos', 'url')
    op.drop_column('eventospeedmeeting', 'url')
    op.drop_column('eventoferiaempresas', 'url')
    op.drop_column('eventocharlas', 'url')
    # ### end Alembic commands ###
